### ISSUE TITLE
[Prometheus Adapter] apiserver was unable to write a JSON response: http2: stream closed

### ISSUE THREAD

**Issue by benjaminhuo** [coreos/kube-prometheus#521]
**What happened?**
Deploy prometheus adapter with kube-prometheus
Got below error in prometheus adapter pod log(repeat every 30 seconds):
```
I0506 11:28:29.190304       1 adapter.go:93] successfully using in-cluster auth
I0506 11:28:29.624391       1 serving.go:273] Generated self-signed cert (/var/run/serving-cert/apiserver.crt, /var/run/serving-cert/apiserver.key)
I0506 11:28:30.131352       1 serve.go:96] Serving securely on [::]:6443
E0506 11:28:53.628657       1 writers.go:149] apiserver was unable to write a JSON response: http2: stream closed
E0506 11:28:53.628687       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
E0506 11:28:53.628699       1 writers.go:149] apiserver was unable to write a JSON response: http2: stream closed
E0506 11:28:53.630557       1 writers.go:149] apiserver was unable to write a JSON response: http2: stream closed
E0506 11:28:53.630851       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
E0506 11:28:53.632975       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
```

**Did you expect to see some different?**
No errors

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f manifests

**Environment**

* Prometheus Adapter version:
  v0.5.0 , Same issue with v0.6.0, 
  adapter log similar error and then panics with v0.7.0 , error logs are
```shell
I0507 04:28:55.121299       1 dynamic_serving_content.go:129] Starting serving-cert::/var/run/serving-cert/apiserver.crt::/var/run/serving-cert/apiserver.key
I0507 04:28:55.121318       1 tlsconfig.go:219] Starting DynamicServingCertificateController
I0507 04:28:55.121548       1 configmap_cafile_content.go:205] Starting client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0507 04:28:55.121558       1 shared_informer.go:197] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0507 04:28:55.221420       1 shared_informer.go:204] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file 
I0507 04:28:55.221677       1 shared_informer.go:204] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file 
E0507 04:29:23.979358       1 writers.go:105] apiserver was unable to write a JSON response: http2: stream closed
E0507 04:29:23.979384       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
E0507 04:29:23.980432       1 writers.go:105] apiserver was unable to write a JSON response: http2: stream closed
E0507 04:29:23.980764       1 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference
goroutine 356 [running]:
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc0033c0180)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/filters/timeout.go:108 +0x107
panic(0x1861bc0, 0x2a840f0)
	/usr/lib/golang/src/runtime/panic.go:679 +0x1b2
compress/gzip.(*Writer).Write(0xc003226000, 0xc003388f80, 0x71, 0x71, 0x30, 0x1920b00, 0xc0037a8d01)
	/usr/lib/golang/src/compress/gzip/gzip.go:168 +0x237
k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Write(0xc001ebc0a0, 0xc003388f80, 0x71, 0x71, 0xc003388f80, 0x71, 0x71)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/handlers/responsewriters/writers.go:182 +0x54e
k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x1ab3a63, 0x10, 0x7fa9dc4292c8, 0xc002b481e0, 0x7fa9dc6a8ed8, 0xc0001fc020, 0xc003646300, 0xc8, 0x1d597a0, 0xc001ebc050)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/handlers/responsewriters/writers.go:117 +0x389
k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x1d8e6e0, 0xc0005d50e0, 0x1d8e920, 0x2ac4d18, 0x0, 0x0, 0x0, 0x0, 0x7fa9dc6a8ed8, 0xc0001fc020, ...)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/handlers/responsewriters/writers.go:251 +0x555
k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).ServeHTTP(0xc003a22d80, 0x7fa9dc6a8ed8, 0xc0001fc020, 0xc003646300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/discovery/version.go:81 +0x18f
k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).handle(...)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/discovery/version.go:77
github.com/emicklei/go-restful.(*Container).dispatch(0xc0005579e0, 0x7fa9dc6a8ed8, 0xc0001fc020, 0xc003646300)
	/home/sur/src/redhat/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:288 +0xa4f
github.com/emicklei/go-restful.(*Container).Dispatch(...)
	/home/sur/src/redhat/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:199
k8s.io/apiserver/pkg/server.director.ServeHTTP(0x1ac198d, 0x1a, 0xc0005579e0, 0xc0004bebd0, 0x7fa9dc6a8ed8, 0xc0001fc020, 0xc003646300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/handler.go:146 +0x4d3
k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7fa9dc6a8ed8, 0xc0001fc020, 0xc003646300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/filters/authorization.go:64 +0x512
net/http.HandlerFunc.ServeHTTP(0xc000491dc0, 0x7fa9dc6a8ed8, 0xc0001fc020, 0xc003646300)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7fa9dc6a8ed8, 0xc0001fc020, 0xc003646300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/filters/maxinflight.go:160 +0x5dc
net/http.HandlerFunc.ServeHTTP(0xc001cdc750, 0x7fa9dc6a8ed8, 0xc0001fc020, 0xc003646300)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7fa9dc6a8ed8, 0xc0001fc020, 0xc003646300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/filters/impersonation.go:50 +0x1fe6
net/http.HandlerFunc.ServeHTTP(0xc000491e00, 0x7fa9dc6a8ed8, 0xc0001fc020, 0xc003646300)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7fa9dc6a8ed8, 0xc0001fc020, 0xc003646200)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/filters/authentication.go:131 +0xa8c
net/http.HandlerFunc.ServeHTTP(0xc0004cf4a0, 0x7fa9dc6a8ed8, 0xc0001fc020, 0xc003646200)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc0033c0180, 0xc001cd69c0, 0x1d93160, 0xc0001fc020, 0xc003646200)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/filters/timeout.go:113 +0xd0
created by k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/filters/timeout.go:99 +0x1cb
```

* Prometheus Operator version:

  v0.38.1

* Kubernetes version information:

  v1.17.3

* Similar issue found
   https://github.com/helm/charts/issues/18576

@s-urbaniak just wondering if you're aware of this issue? Thanks

**Comment by metost** [comment]
I'm seeing the same error, I have deployed prometheus-adapter using helm chart.

```
 E0507 07:38:51.876164       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
 E0507 07:38:51.876197       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
 E0507 07:38:51.877136       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
 I0507 07:38:51.877356       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1: (7.956453ms) 200 [Go-http-client/2.0 xx.xx.xx.xx:46804]
 E0507 07:38:51.878261       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
 E0507 07:38:51.878425       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
 I0507 07:38:51.879853       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1: (10.392531ms) 200 [Go-http-client/2.0 xx.xx.xx.xx:46804]
 E0507 07:38:51.881124       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
 E0507 07:38:51.881573       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
 E0507 07:38:51.882272       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
 I0507 07:38:51.882723       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1: (13.126018ms) 200 [Go-http-client/2.0 xx.xx.xx.xx:46804]
 E0507 07:38:51.883834       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
 I0507 07:38:51.884984       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1: (15.38869ms) 200 [Go-http-client/2.0 xx.xx.xx.xx:46804]
 E0507 07:38:51.886106       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
 I0507 07:38:51.887251       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1: (17.849668ms) 200 [Go-http-client/2.0 xx.xx.xx.xx:46804]
```

**Comment by brancz** [comment]
@serathius iirc you commented somewhere the other day that this is a custom-metrics-server provider problem?

**Comment by serathius** [comment]
Yes, based on problem occurring in both Prometheus and Stackdriver adapter and updating api-machinery dependencies not helping.

**Comment by benjaminhuo** [comment]
@serathius Thanks for the response. Just wondering if this error affect the functionality of prometheus adapter and how?

**Comment by benjaminhuo** [comment]
In my tests, it seems that this error doesn't affect the functionality of prometheus adapter.
I can run custom metrics HPA test and get metrics using kubectl top nodes/pods

But it's still a bit noisy to get these errors :)

**Comment by jaanhio** [comment]
@benjaminhuo when you say it doesnt affect functionality of prometheus adapter, does it mean you are able to query the metrics from http://localhost:8001/apis/custom.metrics.k8s.io/v1beta1/ ? i also noticed i got this error when i ran `kubectl top node`. 

`Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)` 
will this affect pulling of metrics from custom metric server?

**Comment by benjaminhuo** [comment]
yes @jaanhio ,  kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1 works.
I guess you'd have to delete heapster stuff first

**Comment by benjaminhuo** [comment]
close this issue and track the problem in prometheus adapter's https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/292
