### ISSUE TITLE
[Prometheus Adapter] Panic after deploying prometheus adapter v0.7.0

### ISSUE THREAD

**Issue by benjaminhuo** [coreos/kube-prometheus#530]
**What happened?**
Log shows prometheus adapter panics after applying v0.7.0.
v0.6.0 and v0.5.0 is fine.
```
I0514 02:44:02.467143       1 secure_serving.go:178] Serving securely on [::]:6443
I0514 02:44:02.467160       1 tlsconfig.go:219] Starting DynamicServingCertificateController
I0514 02:44:02.566770       1 shared_informer.go:204] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file 
I0514 02:44:02.566775       1 shared_informer.go:204] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file 
E0514 02:44:27.422599       1 writers.go:105] apiserver was unable to write a JSON response: http2: stream closed
E0514 02:44:27.422625       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
E0514 02:44:27.423943       1 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference
goroutine 556 [running]:
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc0038aa060)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/filters/timeout.go:108 +0x107
panic(0x1861bc0, 0x2a840f0)
	/usr/lib/golang/src/runtime/panic.go:679 +0x1b2
compress/gzip.(*Writer).Write(0xc0011c00b0, 0xc003b90900, 0x71, 0x71, 0x30, 0x1920b00, 0xc001edad01)
	/usr/lib/golang/src/compress/gzip/gzip.go:168 +0x237
k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Write(0xc00384e0a0, 0xc003b90900, 0x71, 0x71, 0xc003b90900, 0x71, 0x71)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/handlers/responsewriters/writers.go:182 +0x54e
k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x1ab3a63, 0x10, 0x7f30c54b4c30, 0xc0001fc820, 0x7f30c54b4820, 0xc001454008, 0xc0011ac300, 0xc8, 0x1d597a0, 0xc00384e050)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/handlers/responsewriters/writers.go:117 +0x389
k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x1d8e6e0, 0xc0006f0540, 0x1d8e920, 0x2ac4d18, 0x0, 0x0, 0x0, 0x0, 0x7f30c54b4820, 0xc001454008, ...)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/handlers/responsewriters/writers.go:251 +0x555
k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).ServeHTTP(0xc003042b40, 0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/discovery/version.go:81 +0x18f
k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).handle(...)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/discovery/version.go:77
github.com/emicklei/go-restful.(*Container).dispatch(0xc000ab9680, 0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/home/sur/src/redhat/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:288 +0xa4f
github.com/emicklei/go-restful.(*Container).Dispatch(...)
	/home/sur/src/redhat/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:199
k8s.io/apiserver/pkg/server.director.ServeHTTP(0x1ac198d, 0x1a, 0xc000ab9680, 0xc00014a7e0, 0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/handler.go:146 +0x4d3
k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/filters/authorization.go:64 +0x512
net/http.HandlerFunc.ServeHTTP(0xc002ea9d80, 0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/filters/maxinflight.go:160 +0x5dc
net/http.HandlerFunc.ServeHTTP(0xc002fd1890, 0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/filters/impersonation.go:50 +0x1fe6
net/http.HandlerFunc.ServeHTTP(0xc002ea9dc0, 0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f30c54b4820, 0xc001454008, 0xc0011ac200)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/filters/authentication.go:131 +0xa8c
net/http.HandlerFunc.ServeHTTP(0xc000203630, 0x7f30c54b4820, 0xc001454008, 0xc0011ac200)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc0038aa060, 0xc003000aa0, 0x1d93160, 0xc001454008, 0xc0011ac200)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/filters/timeout.go:113 +0xd0
created by k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/filters/timeout.go:99 +0x1cb

goroutine 633 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x17d3080, 0xc00352b350)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc001d95c90, 0x1, 0x1)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:48 +0x82
panic(0x17d3080, 0xc00352b350)
	/usr/lib/golang/src/runtime/panic.go:679 +0x1b2
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc003000aa0, 0x1d8c920, 0xc0001120e0, 0xc0011ac200)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/filters/timeout.go:119 +0x486
k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x1d8c920, 0xc0001120e0, 0xc0011ac100)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/filters/waitgroup.go:47 +0x10f
net/http.HandlerFunc.ServeHTTP(0xc002fd18c0, 0x1d8c920, 0xc0001120e0, 0xc0011ac100)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x1d8c920, 0xc0001120e0, 0xc0011ac000)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/filters/requestinfo.go:39 +0x274
net/http.HandlerFunc.ServeHTTP(0xc002fd18f0, 0x1d8c920, 0xc0001120e0, 0xc0011ac000)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x1d80860, 0xc000526228, 0xc0002fd300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/httplog/httplog.go:89 +0x2ca
net/http.HandlerFunc.ServeHTTP(0xc003000ac0, 0x1d80860, 0xc000526228, 0xc0002fd300)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x1d80860, 0xc000526228, 0xc0002fd300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/filters/wrap.go:51 +0x13e
net/http.HandlerFunc.ServeHTTP(0xc003000ae0, 0x1d80860, 0xc000526228, 0xc0002fd300)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc002fd1920, 0x1d80860, 0xc000526228, 0xc0002fd300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc00029f340, 0x1d80860, 0xc000526228, 0xc0002fd300)
	/usr/lib/golang/src/net/http/server.go:2802 +0xa4
net/http.initNPNRequest.ServeHTTP(0x1d92d20, 0xc003097e60, 0xc0005ff500, 0xc00029f340, 0x1d80860, 0xc000526228, 0xc0002fd300)
	/usr/lib/golang/src/net/http/server.go:3366 +0x8d
golang.org/x/net/http2.(*serverConn).runHandler(0xc00314a780, 0xc000526228, 0xc0002fd300, 0xc003897be0)
	/home/sur/src/redhat/go/pkg/mod/golang.org/x/net@v0.0.0-20191004110552-13f9640d40b9/http2/server.go:2149 +0x9f
created by golang.org/x/net/http2.(*serverConn).processHeaders
	/home/sur/src/redhat/go/pkg/mod/golang.org/x/net@v0.0.0-20191004110552-13f9640d40b9/http2/server.go:1883 +0x4eb
E0514 02:44:27.423982       1 wrap.go:39] apiserver panic'd on GET /apis/custom.metrics.k8s.io/v1beta1
I0514 02:44:27.424206       1 log.go:172] http2: panic serving 10.233.70.0:5953: runtime error: invalid memory address or nil pointer dereference
goroutine 556 [running]:
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc0038aa060)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/filters/timeout.go:108 +0x107
panic(0x1861bc0, 0x2a840f0)
	/usr/lib/golang/src/runtime/panic.go:679 +0x1b2
compress/gzip.(*Writer).Write(0xc0011c00b0, 0xc003b90900, 0x71, 0x71, 0x30, 0x1920b00, 0xc001edad01)
	/usr/lib/golang/src/compress/gzip/gzip.go:168 +0x237
k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Write(0xc00384e0a0, 0xc003b90900, 0x71, 0x71, 0xc003b90900, 0x71, 0x71)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/handlers/responsewriters/writers.go:182 +0x54e
k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x1ab3a63, 0x10, 0x7f30c54b4c30, 0xc0001fc820, 0x7f30c54b4820, 0xc001454008, 0xc0011ac300, 0xc8, 0x1d597a0, 0xc00384e050)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/handlers/responsewriters/writers.go:117 +0x389
k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x1d8e6e0, 0xc0006f0540, 0x1d8e920, 0x2ac4d18, 0x0, 0x0, 0x0, 0x0, 0x7f30c54b4820, 0xc001454008, ...)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/handlers/responsewriters/writers.go:251 +0x555
k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).ServeHTTP(0xc003042b40, 0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/discovery/version.go:81 +0x18f
k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).handle(...)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/discovery/version.go:77
github.com/emicklei/go-restful.(*Container).dispatch(0xc000ab9680, 0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/home/sur/src/redhat/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:288 +0xa4f
github.com/emicklei/go-restful.(*Container).Dispatch(...)
	/home/sur/src/redhat/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:199
k8s.io/apiserver/pkg/server.director.ServeHTTP(0x1ac198d, 0x1a, 0xc000ab9680, 0xc00014a7e0, 0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/handler.go:146 +0x4d3
k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/filters/authorization.go:64 +0x512
net/http.HandlerFunc.ServeHTTP(0xc002ea9d80, 0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/filters/maxinflight.go:160 +0x5dc
net/http.HandlerFunc.ServeHTTP(0xc002fd1890, 0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/filters/impersonation.go:50 +0x1fe6
net/http.HandlerFunc.ServeHTTP(0xc002ea9dc0, 0x7f30c54b4820, 0xc001454008, 0xc0011ac300)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f30c54b4820, 0xc001454008, 0xc0011ac200)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/endpoints/filters/authentication.go:131 +0xa8c
net/http.HandlerFunc.ServeHTTP(0xc000203630, 0x7f30c54b4820, 0xc001454008, 0xc0011ac200)
	/usr/lib/golang/src/net/http/server.go:2007 +0x44
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc0038aa060, 0xc003000aa0, 0x1d93160, 0xc001454008, 0xc0011ac200)
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/filters/timeout.go:113 +0xd0
created by k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/home/sur/src/redhat/go/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/filters/timeout.go:99 +0x1cb
```
**How to reproduce it (as minimally and precisely as possible)**:
Deploy the latest kube-prometheus/manifest

**Environment**
Prometheus Adapter version:
v0.7.0
* Prometheus Operator version:
v0.38.1

* Kubernetes version information:
v1.17.3

**Comment by brancz** [comment]
Can you report this on the prometheus adapter itself?

**Comment by benjaminhuo** [comment]
Sure will do

**Comment by benjaminhuo** [comment]
close this issue and track it in adapter's  https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/291
